# Server
server:
  port: 80

spring:
  # DBCP
  datasource:
    url: jdbc:h2:mem:hellojpa;
    driver-class-name: org.h2.Driver
    username: abc
    password: abc
  # H2
  h2:
    console:
      enabled: true
      path: /h2
  # Devtools
  devtools:
    restart:
      enabled: false
  # JPA
  jpa:
    show-sql: true